version: "3"
name: inception

volumes:
  wp-db:
  wp-site:

networks:
  inception:
    external: false

services:
  nginx:
    container_name: inception-nginx
    networks:
      - inception
    environment:
      - TZ=Europe/Paris
    depends_on:
      - wordpress-php
      - db
    volumes:
      - wp-site:/var/www/html
    ports:
      - "443:443"
    restart: unless-stopped

  wordpress-php:
    container_name: inception-workp-php
    networks:
      - inception
    environment:
      - TZ=Europe/Paris
    volumes:
      - wp-site:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: inception-db
    networks:
      - inception
    environment:
      - TZ=Europe/Paris
    volumes:
      - wp-db:/var/lib/mysql
    restart: unless-stopped
