name: inception

volumes:
  wp-db:
  wp-site:

networks:
  inception:
    external: false

services:
  nginx:
    container_name: inception-nginx
    build:
      context: .
      dockerfile: docker/nginx/dockerfile
    networks:
      - inception
    environment:
      - TZ=Europe/Paris
    depends_on:
      - wordpress-php
      - db
    volumes:
      - wp-site:/var/www/html
    ports:
      - "443:443"
    restart: unless-stopped

  wordpress-php:
    container_name: inception-wordp-php
    build:
      context: .
      dockerfile: docker/wordpress/dockerfile
    networks:
      - inception
    environment:
      - PHP_MEMORY_LIMIT="512M"
      - PHP_MAX_UPLOAD="50M"
      - TZ=Europe/Paris
    volumes:
      - wp-site:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: inception-db
    build:
      context: .
      dockerfile: docker/mariadb/Dockerfile
    networks:
      - inception
    environment:
      - MYSQL_ROOT_PASSWORD="alpine"
      - MYSQL_PASSWORD="alpine"
      - MYSQL_USER="kanel"
      - MYSQL_DATABASE="knl"
      - TZ=Europe/Paris
    volumes:
      - wp-db:/var/lib/mysql
    restart: unless-stopped
