name: inception

include:
  - path: ./docker/composes/nginx.yml
    project_directory: ./
  - path: ./docker/composes/wordp-php.yml
    project_directory: ./
  - path: ./docker/composes/db.yml
    project_directory: ./
  - path: ./docker/composes/dev/nginx.yml
    project_directory: ./
  - path: ./docker/composes/dev/wordp-php.yml
    project_directory: ./
  - path: ./docker/composes/dev/db.yml
    project_directory: ./

networks:
  inception:
    name: inception
    external: false
