services:
  static-site:
    build: static-site
    ports:
      - 8080:443
    depends_on:
      - nginx
    environment:
      - TZ=Europe/Paris
      - NGINX_SSL_KEY_FILE=/etc/nginx/ssl/kanel-wp.key
      - NGINX_SSL_CERT_FILE=/etc/nginx/ssl/kanel-wp.crt
  ftp:
    build: vsftp
    ports:
      - 2100:21
      - 30000-30100:30000-30100
    depends_on:
      nginx:
        condition: service_started
      wordpress-php:
        condition: service_healthy

