services:
  nginx-dev:
    container_name: inception-nginx
    build:
      context: .
      dockerfile: docker/images/nginx/Dockerfile
    networks:
      - inception
    environment:
      - TZ=Europe/Paris
      - NGINX_PHP_HOST=inception-wordp-php
      - NGINX_SSL_KEY_FILE=/etc/nginx/ssl/adjoly-wp.key
      - NGINX_SSL_CERT_FILE=/etc/nginx/ssl/adjoly-wp.crt
    depends_on:
      wordpress-php-dev:
        condition: service_healthy
      db-dev:
        condition: service_healthy
    volumes:
      - wp-site:/var/www/html
      - ./configs/nginx/templates-dev:/etc/nginx/templates
      - ./configs/nginx/entry:/docker-entrypoint.d
    ports:
      - "443:443"
    restart: unless-stopped
    profiles:
      - dev
